### ISSUE TITLE
FR: ek_Global startup settings

### ISSUE THREAD

**Issue by Alucast** [edkashinsky/reaper-reableton-scripts#1]
It would be cool if we could set the zoom limit to a certain time frame for starters, optionally maybe? Because in a early empty project with say two items, it limits it to a really short zone so I can't zoom out so much and sometimes I like to zoom out a bit more to have a general view and work later on the timeline, I like the function but I'd like to have a bit more zoom out headroom, maybe not the extreme zoom by default but just a bit more of what the items limit to, like a handle, a 20 min handle size or something. I hope I'm making myself clear haha english is not my first language. Thanks!

**Comment by edkashinsky** [comment]
Hey! Thank you for feature request! What if I add a new field in percents, where you can set additional offset for limitation of max view. 
<img width="529" alt="Снимок экрана 2023-02-09 в 11 20 45" src="https://user-images.githubusercontent.com/26724113/217785298-c1b43d26-8781-43c5-b73d-f20bd91bd48b.png">
For example, if you have 2 items in arrange view with 22 sec duration and set this offset = 100%, your max zoom view will be 44 sec. What do you think?

**Comment by Alucast** [comment]
Sorry, didn't see you replied on this one! But yeah, that sounds excellent! Thank you for considering it.

**Comment by Alucast** [comment]
Hi! I was wondering if you were going to release this feature?

**Comment by edkashinsky** [comment]
Yes, I'm working on it. Just need more time

**Comment by Alucast** [comment]
Ah, sorry, that's ok! I kind of thought you had forgotten hahaha but no, take your time, no pressure thank you

**Comment by edkashinsky** [comment]
Hey, @alucast! I added option "Offset from the edge item" in "ek_Global startup action settings" window by your feature request. Thank you for it and text me, if you have problems with that or you have new requests!

Please synchronize your scripts in ReaPack and don't forget to re-open Reaper

**Comment by Alucast** [comment]
Cool man! I'll try it out in these following days and write up if anything shows up. Thank you so much.
