### ISSUE TITLE
BUG : Global startup action crashes Reaper 

### ISSUE THREAD

**Issue by Alucast** [edkashinsky/reaper-reableton-scripts#2]
In a clean session, if you create a track, record arm it and then delete it, it crashes reaper. I know this is from this global startup script because when I took it out of my sws global startup actions this didn't happen. 

I only have active the automatically adjust grid, Automatically focus to MIDI editor and timestamp backups on, which is weird..

I'm on mac mojave 10.14

https://i.imgur.com/jyXB6IA.gif

**Comment by kashinskyloona** [comment]
Hey, @alucast! Thank you for your bug report! I can't replicate this behavior on my laptop with your settings. Could you write to me in my telegram http://t.me/edkashinsky and we will try to determine the steps to reproduce the bug

**Comment by edkashinsky** [comment]
Hey, @alucast! Thank you for your bug report! I can't replicate this behavior on my laptop with your settings. Could you write to me in my telegram http://t.me/edkashinsky and we will try to determine the steps to reproduce the error

**Comment by Alucast** [comment]
I forgot to mention (maybe not important really) I'm using the latest Reaper official version 6.78 and yeah, I'll message you tomorrow, thanks!

**Comment by Alucast** [comment]
Ok so update. I forgot I had a global action in your Additional global startup action setting and that other action (ReaLlm) was the one causing issues. Sorry about the confusion! And thanks for your scripts and help. 

I'm kind of relieved tbh because I actually like your script a lot.

**Comment by edkashinsky** [comment]
Thank you and I relieved too, because I get tense when I hear that something works differently than on my laptop) So it's great!
