### ISSUE TITLE
FR: Zoom limit affects recording limit (duh)

### ISSUE THREAD

**Issue by Alucast** [edkashinsky/reaper-reableton-scripts#3]
Hi, it's me again hehe 😅 I've been using your zoom limit with the offset and I find it quite useful so thanks for that BUT I've found a small inconvenience or nitpick per se. 

If I start an empty project, simply to record something so I won't forget it or just to flesh it out I bump against the wall with the way it also limits recording, because well not only it zooms the view but also the length of where you can record so any time I try to record something it just stops right away, because of the view limit of course and it's an empty project so there's nothing to offset from. I have to draw an empty midi item far away so the offset doesn't cut off my recording. 

I don't know if it would be possible to add an option or input box to insert a value, be it beats or hours:minutes:seconds where it respects that for an empty project and then when you're working on it and adding stuff, it uses the offset limit you added before to now limit everything. Or maybe not limit when recording? Idk which could be easier, any would work for me tbh.

So using this say I have a 10 beat intro so I have a 20 beat default recording pad with that option so I can record a few bars now (20) without it cutting of my recording time and then after I have items and what not well the other offset works on that so now the view is limited as it was already before.

I don't know if I'm being clear sorry, english is not my first language.

Hope it makes sense! 

EDIT: weird, if I tried to capture the screen with LICEcap to show a clear example but the recording  now doesn't stop, and when I'm not recording the screen it stops at bar 6 every time. Funny.

**Comment by edkashinsky** [comment]
Hey, @alucast! Thank you again for your bug request! I'm glad that you use my scripts and even want to make it better. Seriously, I really appreciate it! 
I fixed that in 1.0.26 version of "ek_Global startup action" so just synchronize scripts via ReaPack and re-open Reaper. Now if you record something, project limit will be turn off. So you can walk anywhere in project without adding dummy items

**Comment by Alucast** [comment]
Gad damn! What a quick fix hahaha it works perfectly, thank you so much man! Your scripts have been a blessing, specially global startup action. Thanks for your stuff! Have a great day.
