### ISSUE TITLE
"Automatically limit zoom to size of project" changes project settings

### ISSUE THREAD

**Issue by jeremybernstein** [edkashinsky/reaper-reableton-scripts#5]
Hi there, I've been having a weird symptom which I've now narrowed down to the Global Startup Action script, in particular the "Automatically limit zoom to size of project" feature. This is causing the v7 project setting "Limit project length" to turn on and reset to the length of the project (the time of the end of the last item) every time the transport is enabled, which results in some annoying side effects (like not being able to record a new item after the last item in some cases).

macOS 13.6.1 with REAPER 7.02 (but I've been having this issue since the v7 pre-releases, I only just now discovered the connection to your (otherwise wonderful) script.

To reproduce:
* enable "Automatically limit zoom" in the global script
* in project settings (assume there's at least one item), DISABLE the "limit project length" setting
* play the project for a second
* check the setting again -- it's been enabled and the length set to the end of the last item

**Comment by edkashinsky** [comment]
Hey, @jeremybernstein! Thank you for your bug report! I fixed that in new version of Global Statrtup Action (version 1.0.39), could you synchronize your ReaPack and check it out?

**Comment by jeremybernstein** [comment]
Thank you @edkashinsky -- it's still doing it for me after updating the script and restarting REAPER.

**Comment by edkashinsky** [comment]
You are correct, Global Startup Action is enabling "limit project length" option, if "Automatically limit zoom" is enabled, even you disable it manually. But weird symptom you faced with should be solved. For example, if you move edit cursor behind the last media item, playback will be working or if you record behind project limit. Could you check script for your annoying side effects? Everything works ok?

**Comment by jeremybernstein** [comment]
OK I see, thanks @edkashinsky . On a very first quick test, yes, the annoying side effects seem to be gone (yay!), but I'll keep an eye on it and let you know when I have more time to spend with it.

**Comment by edkashinsky** [comment]
Great news) I hope, everything will be fine! Anyway, let me know, if you faced with new issues
